language: java
sudo: required
jdk:
  - oraclejdk8
env:  
  global:  
    - DISPLAY=:99.0  
cache:  
  directories:  
   - $HOME/.m2  

notifications:
  email:
    recipients:
      - vitruv-build@ira.uni-karlsruhe.de

# Handle git submodules yourself
git:
    submodules: false

# Enable UI
before_install:
    - sh -e /etc/init.d/xvfb start - sleep 10
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/installMaven.sh
    - "echo \"export MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx2g -XX:MaxPermSize=2048m'\" > ~/.mavenrc"
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh framework releng/tools.vitruv.updatesite.aggregated final vitruv-tools updatesite